### CREATE
POST {{baseUrl}}/todos
Content-Type: application/json

{
  "title": "할일1",
  "description": "할일 설명1",
  "completed": false
}

### READ 1
GET {{baseUrl}}/todos/1

### READ 2
GET {{baseUrl}}/todos

### UPDATE
PUT {{baseUrl}}/todos/1
Content-Type: application/json

{
  "title": "수정된 할일1",
  "description": "수정된 할일 설명1",
  "completed": true
}

### DELETE
DELETE {{baseUrl}}/todos/1
